### ISSUE TITLE
Introduce CRAN example app before walking through implementation

### ISSUE THREAD

**Issue by cpsievert** [jcheng5/shiny-book#7]
In these sort of scenarios I find it helpful to work backwards: first show the completed app (maybe link to a gif or video demoing the interactive behavior). Then you could even make some exercises for the reader before walking through the details, could ask:

(1) What are the reactive values in this app? Asking this question first and partially addressing it right away can help explain why your script has these "configuration variables"
(2) What are the outputs?
(3) Can you predict how reactive expressions might be useful for this app?

Then you could introduce the data and walk through the steps

**Comment by hadley** [comment]
I think the motivation here is to imagine that you already have a script (because that's what most people already have). But I do like the idea of providing some simple apps and then asking users to identify the inputs and outputs, and to think about about the reactive graph (imagining the expression that might exist behind the scenes). I think those will make good exercises.
